services:
  checklistapi_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgres/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  checklistapi_app:
    image: checklistapi_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - checklistapi_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@checklistapi_database:5432/app_db

volumes:
  pgdata:
