name: pipeline
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Instalar o python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            
            - name: Instalar o poetry
              run: "pipx install poetry"